#!/usr/bin/env bash
# One-time local dev setup: JDK 21 + Android SDK paths (gitignored files).
#
#   cd "/path/to/Med-Pearls-Android"
#   ./scripts/setup-local-env.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

find_jdk21() {
  is_supported_java() {
    local java_bin="$1/bin/java"
    [[ -x "$java_bin" ]] || return 1
    local version
    version=$("$java_bin" -version 2>&1 | head -1)
    [[ "$version" != *\"25.* && "$version" != *\"26.* ]]
  }
  local path
  local candidates=(
    "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
    "/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home"
    "$HOME/Applications/Android Studio.app/Contents/jbr/Contents/Home"
  )
  for path in "${candidates[@]}"; do
    if is_supported_java "$path"; then echo "$path"; return 0; fi
  done
  if command -v /usr/libexec/java_home >/dev/null 2>&1; then
    local j21 j17
    j21=$(/usr/libexec/java_home -v 21 2>/dev/null || true)
    if [[ -n "$j21" ]] && is_supported_java "$j21"; then echo "$j21"; return 0; fi
    j17=$(/usr/libexec/java_home -v 17 2>/dev/null || true)
    if [[ -n "$j17" ]] && is_supported_java "$j17"; then echo "$j17"; return 0; fi
  fi
  return 1
}

find_android_sdk() {
  local candidates=()
  [[ -n "${ANDROID_HOME:-}" ]] && candidates+=("$ANDROID_HOME")
  [[ -n "${ANDROID_SDK_ROOT:-}" ]] && candidates+=("$ANDROID_SDK_ROOT")
  candidates+=(
    "$HOME/Library/Android/sdk"
    "/Volumes/AI_SSD/Android/Sdk"
    "/Volumes/AI_SSD/Android/SDK"
  )
  for path in "${candidates[@]}"; do
    if [[ -d "$path/platform-tools" ]]; then
      echo "$path"
      return 0
    fi
  done
  return 1
}

JDK_HOME="$(find_jdk21)" || {
  echo "error: No JDK 17 or 21 found (Java 25 breaks Gradle)." >&2
  echo "  brew install --cask temurin@21" >&2
  exit 1
}

SDK_DIR="$(find_android_sdk)" || {
  echo "error: Android SDK not found." >&2
  echo "  Open Android Studio → SDK Manager → install Android SDK" >&2
  echo "  Default path: \$HOME/Library/Android/sdk" >&2
  echo "  Or set ANDROID_HOME and re-run." >&2
  exit 1
}

echo "JDK:  $JDK_HOME"
"$JDK_HOME/bin/java" -version 2>&1 | head -1
echo "SDK:  $SDK_DIR"

mkdir -p gradle
cat > gradle/config.properties <<EOF
# Generated by scripts/setup-local-env.sh — do not commit
java.home=$JDK_HOME
EOF

cat > local.properties <<EOF
# Generated by scripts/setup-local-env.sh — do not commit
sdk.dir=$SDK_DIR
EOF

mkdir -p .idea
cat > .idea/gradle.xml <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="GradleMigrationSettings" migrationVersion="1" />
  <component name="GradleSettings">
    <option name="linkedExternalProjectsSettings">
      <GradleProjectSettings>
        <option name="testRunner" value="CHOOSE_PER_TEST" />
        <option name="externalProjectPath" value="$PROJECT_DIR$" />
        <option name="gradleJvm" value="#GRADLE_LOCAL_JAVA_HOME" />
        <option name="modules">
          <set>
            <option value="$PROJECT_DIR$" />
            <option value="$PROJECT_DIR$/app" />
          </set>
        </option>
      </GradleProjectSettings>
    </option>
  </component>
</project>
EOF

echo ""
echo "Wrote gradle/config.properties, local.properties, .idea/gradle.xml"
echo "Test: ./gradlew assembleDebug"
